// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChHohIQ_iBk5vAjayT02eiDxbeEdcJ5wk',
    appId: '1:541652343600:web:7585d7c13a5a5d4a40c6f5',
    messagingSenderId: '541652343600',
    projectId: 'rent-car-8c572',
    authDomain: 'rent-car-8c572.firebaseapp.com',
    databaseURL: 'https://rent-car-8c572-default-rtdb.firebaseio.com',
    storageBucket: 'rent-car-8c572.appspot.com',
    measurementId: 'G-6RYG02FXMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4xEshbgvurLxA-D6vLWXDjWkzdzGIZjk',
    appId: '1:541652343600:android:3a5218b07556216240c6f5',
    messagingSenderId: '541652343600',
    projectId: 'rent-car-8c572',
    storageBucket: 'rent-car-8c572.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzY-UAKU_7jfYpcK74IN3EHir_q7eanjw',
    appId: '1:541652343600:ios:412adfac301cb74b40c6f5',
    messagingSenderId: '541652343600',
    projectId: 'rent-car-8c572',
    storageBucket: 'rent-car-8c572.appspot.com',
    iosClientId: '541652343600-dctjr8eu84b31mh6juvjfi3mmrakd4ts.apps.googleusercontent.com',
    iosBundleId: 'br.com.joaov.mobileManagerCar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzY-UAKU_7jfYpcK74IN3EHir_q7eanjw',
    appId: '1:541652343600:ios:412adfac301cb74b40c6f5',
    messagingSenderId: '541652343600',
    projectId: 'rent-car-8c572',
    databaseURL: 'https://rent-car-8c572-default-rtdb.firebaseio.com',
    storageBucket: 'rent-car-8c572.appspot.com',
    iosClientId: '541652343600-dctjr8eu84b31mh6juvjfi3mmrakd4ts.apps.googleusercontent.com',
    iosBundleId: 'br.com.joaov.mobileManagerCar',
  );
}
